### ISSUE TITLE
Duplicate prefixes

### ISSUE THREAD

**Issue by sereyn** [the-qa-company/qEndpoint#11]
### Description of the issue

**Endpoint used:** `/api/endpoint/sparql`

**Description:**
The query is an `INSERT` and if I use a `PREFIX` such as `rdf`. The server response is:
```
error: "Internal Server Error"
message: "Multiple prefix declarations for prefix 'rdf'"
path: "/api/endpoint/sparql"
status: 500
timestamp: "2022-06-08T13:50:57.537+0000"
```
It's because the server adds default prefixes

### Excepted behavior

We should remove duplicate prefixes

### Obtained behavior

Duplicate prefixes are not removed

### How to reproduce

```bash
curl 'http://localhost:1234/api/endpoint/sparql' \
  -H 'Accept: text/plain,*/*;q=0.9' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,fr;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Origin: http://localhost:3001' \
  -H 'Referer: http://localhost:3001/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'timeout: 5' \
  --data-raw 'update=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0AINSERT%20DATA%20%7B%0A%20%20%3Chttps%3A%2F%2Fme.com%2Fa%3E%20%3Chttps%3A%2F%2Fme.com%2Fa%3E%20%3Chttps%3A%2F%2Fme.com%2Fa%3E%20.%0A%7D' \
  --compressed
```

### Endpoint version

1.3.0

### Do I want to contribute to fix it?

Maybe

### Something else?

Your "submit issue" form is a pain 😡

**Comment by ate47** [comment]
I've created this pull request to allow it: https://github.com/eclipse/rdf4j/pull/3993, let's wait for it

**Comment by D063520** [comment]
@ate47 this is a while ago, I think it is in the current release .... and we are already using it, I can still reproduce it though ....

**Comment by ate47** [comment]
It was hot fixed, but I did not took the time to implement [this feature of RDF4J](https://github.com/eclipse/rdf4j/pull/3993) yet.
