### ISSUE TITLE
Releases post v1.3.0 not available on Maven Central

### ISSUE THREAD

**Issue by davidandreoletti** [the-qa-company/qEndpoint#132]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [X] Other

### Description of the issue

[hdtSparqlEndpoint jar v1.6.3](https://search.maven.org/artifact/com.the-qa-company/hdtSparqlEndpoint) is missing. 

### Excepted behavior

Expecting v1.3.0 and onwards to be available on Maven Central.

### Obtained behavior

Most recent release from Maven Central is for example hdtSparqlEndpoint v1.3.0.

### How to reproduce

NA

### Endpoint version

NA

### Do I want to contribute to fix it?

NA

### Something else?

NA

**Comment by ate47** [comment]
Release post 1.3.0 are with the artifact id `qendpoint`

https://search.maven.org/artifact/com.the-qa-company/qendpoint

Where did you find hdtSparqlEndpoint?

**Comment by davidandreoletti** [comment]
Found it in [README's POM declaration](https://github.com/the-qa-company/qEndpoint#back-end)

**Comment by ate47** [comment]
Thanks! An old remnant, it is fixed :)
