### ISSUE TITLE
Lucene store enabled by default with Wikidata

### ISSUE THREAD

**Issue by ate47** [the-qa-company/qEndpoint#228]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [X] Other

### Description of the issue

When the system is indexing a dataset (or download it), it works fine with 10GB, but once the system is loaded, the store is trying to index the dataset, the query is really heavy because of the sort and cause an OOM.

Maybe it would be good to do some optimizations in the store to index HDTs with the LuceneIndex, to disable this feature by default or by adding a warning if the HDT size is too big (like 1B for example)

### Do I want to contribute to fix it?

Yes

**Comment by D063520** [comment]
If the data is only in hdt it is not a problem …. The subjects will be returned grouped and this suffices.

**Comment by ate47** [comment]
> If the data is only in hdt it is not a problem …. The subjects will be returned grouped and this suffices.

Yes, but we do need to put a sort by or a group by in the reindex query because of the delta-store and the HDT triples aren't "sorted enough" to ignore the sort by subject even if they are sorted enough for the Lucene indexing.

**Comment by D063520** [comment]
Maybe a good reason to think about smarter sorting. We can easily create a sorted steam where we grab all matches I the delta we sort them and then we do a 2way sort

**Comment by ate47** [comment]
But we can't say the same about HDT, for SPO and OPS queries, we need to read the shared and the subjects/objects at the same time and do a merge over the strings (or with a map shared->subject/object), something not possible currently with RDF-HDT, then the P is fine, but for the last O/S, we need to use a similar mapping to sort the ids, still not implemented.

For the predicate index I'm not confident enough on how it works to answer.

And all of this is with a simple triple pattern sorting, if the user wants to add a complex (re)index query, it won't work

**Comment by D063520** [comment]
true, I forgot about that detail ....
