### ISSUE TITLE
Remove reindex button if no Lucene indexes is used in the endpoint

### ISSUE THREAD

**Issue by ate47** [the-qa-company/qEndpoint#34]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [X] Frontend (hdt-qs-benchmark)
- [ ] Benchmark (hdt-qs-frontend)
- [ ] Other

### Description of the request

The reindex button in the frontend is calling the `/api/endpoint/reindex` method, but this button can be useless/misleading if the endpoint doesn't have a Lucene node connected to it

### Do I want to contribute to make it?

Maybe

**Comment by ate47** [comment]
@sereyn can you look at it when you would have the time?

I've added the `/api/endpoint/has_index` method returning

```json
{
  "hasLuceneIndex": true
}
```

if this hasLuceneIndex is true, the button should be available, otherwise it shouldn't be visible.

Thanks

**Comment by sereyn** [comment]
Yes sure, doing it ASAP
