### ISSUE TITLE
When uploading quads, upload at least the triples

### ISSUE THREAD

**Issue by D063520** [the-qa-company/qEndpoint#343]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (qendpoint-backend)
- [ ] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the request

I wanted to give a look at this:

wget https://data.dws.informatik.uni-mannheim.de/structureddata/2022-12/quads/dpef.html-embedded-jsonld.nq-00000.gz

and when I load I get:

 curl "http://127.0.0.1:1234/api/endpoint/load" -F "file=@dpef.html-embedded-jsonld.nq-00000.gz"
{"timestamp":"2023-04-15T18:43:40.783+00:00","status":400,"error":"Bad Request","path":"/api/endpoint/load"}

Which makes sense. Still can we upload the dataset and remove the named graph part? What do you think?

### Do I want to contribute to make it?

No

**Comment by ate47** [comment]
Your file has the extension `nq-00000.gz`, rename it to nq.gz or nq.00000.gz and it will work.
