### ISSUE TITLE
Error during docker first run

### ISSUE THREAD

**Issue by lsiciliani** [the-qa-company/qEndpoint#354]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [ ] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the issue

I am encountering a problem downloading the [wikidata docker](https://hub.docker.com/r/qacompany/qendpoint-wikidata)  from a server inside my University.

The issue arises when running the following command:
`sudo docker run -p 1234:8081 --name qendpoint-wikidata --env MEM_SIZE=12G qacompany/qendpoint-wikidata`

At first, the download regularly started, but then there was a timeout error (the estimated time for the completion of the download was around 17h). Now it seems that our IP address has been banned because the download doesn't even start (443 timeout)

More specifically, the output looks like this:
`Search for wikidata_truthy index at https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt
starting...
Downloading the HDT index wikidata_truthy into /app/qendpoint/hdt-store/index_dev.hdt...
--2023-05-08 12:46:14--  https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt
Resolving qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)... 161.3.151.12
Connecting to qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)|161.3.151.12|:443... failed: Connection timed out.
Retrying.`

We have checked that our server can successfully access content hosted abroad. And the download does not start even when using the wget command (`wget https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt`).

### Do I want to contribute to fix it?

Maybe

**Comment by D063520** [comment]
can you share the IP of the university server, so that we can check if it is blocked on our side?

**Comment by D063520** [comment]
@DiaZork what is your best clue about this issue?

**Comment by D063520** [comment]
hi, indeed your IP was blocked. This should happen only if many requests are made from your IP that return errors. Could you try again?

**Comment by lsiciliani** [comment]
Hi, the issue has been solved, and everything seems working now.
Thank you so much for your support.
