### ISSUE TITLE
Failed to download hdt file

### ISSUE THREAD

**Issue by niconical** [the-qa-company/qEndpoint#398]
I want to use `qendpoint-wikidata` in Asia, but downloading data through `https://qanswer-svc4.univ-st-etienne.fr/` is easy to fail. Is there any way to make these data files needed by `qendpoint`?

**Comment by niconical** [comment]
```shell
Length: 37112234712 (35G) [application/octet-stream]
Saving to: ‘wikidata_truthy.hdt.index.v1-1’

wikidata_truthy.hdt   2%[                    ]   1.00G   620KB/s    in 13m 43s

2023-08-21 13:50:45 (1.25 MB/s) - Connection closed at byte 1078486185. Retrying.

--2023-08-21 13:50:46--  (try: 2)  https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt.index.v1-1
Reusing existing connection to qanswer-svc4.univ-st-etienne.fr:443.
Proxy request sent, awaiting response... No data received.
Retrying.

--2023-08-21 13:50:48--  (try: 3)  https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt.index.v1-1
Connecting to 192.168.10.10:16823... connected.
Unable to establish SSL connection.
```

**Comment by D063520** [comment]
Hi @niconical, how did you solve this? I think it is a problem on our infrastructure that the download is slow, we are checking this ....

**Comment by niconical** [comment]
> 

At the beginning, I directly modified the `loadData.sh` and used `wget` to download, but the download was often interrupted. Later I downloaded it using [IDM](https://www.internetdownloadmanager.com/).

**Comment by D063520** [comment]
ok, thank you for reporting, might help also others!
