### ISSUE TITLE
qendpoint does not return `wikibase:label` information for [AUTO_LANGUAGE]

### ISSUE THREAD

**Issue by niconical** [the-qa-company/qEndpoint#399]
I recently installed `qendpoint` via Docker, but there is a problem executing the following SPARQL statement:
```shell
# https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial
SELECT ?child ?childLabel
WHERE
{
  ?child wdt:P22 wd:Q1339;
         wdt:P25 wd:Q57487.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
}
```

qendpoint only displays the information of the `child` column but not the information of the `childLabel` column.

**Comment by D063520** [comment]
Hi,

we support full sparql syntax 1.1 (except named graphs), and unfortunately this:

SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }

is not part of SPARQL 1.1. I think we implemented:

SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }

can you check if this is working?

We can work on a fix for this. Before can you check with  "en"?

**Comment by D063520** [comment]
We would need to change something here:

https://github.com/the-qa-company/qEndpoint/blob/fabe74abeedbd20d2fd958f8c2d845713814779f/qendpoint-store/src/main/java/com/the_qa_company/qendpoint/federation/WikibaseLabelService.java#L131

**Comment by niconical** [comment]
> 

Thanks a lot, It works.

**Comment by D063520** [comment]
Ok, let me check for the AUTO_LANGUAGE ....

**Comment by D063520** [comment]
@niconical I do not know 100% the syntax, does AUTO_LANGUAGE means that you would like to have any language that is attached, up to us to decide?

**Comment by D063520** [comment]
So according to here:

"https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual/el"

it says:

`The Wikidata Query Service website automatically replaces [AUTO_LANGUAGE] with the language code of current user's interface. For example, if the user's UI is in French, the SPARQL's code bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" will be converted to bd:serviceParam wikibase:language "fr,en" before being sent to the query service.`

so it is basically happening in the UI. This means that we cannot implement it in the backend but we need a replacement in the front-end ....

**Comment by D063520** [comment]
@sereyn would it be possible to grab some browser config and to do the replacement also in our front-end?

**Comment by niconical** [comment]
> So according to here:
> 
> "https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual/el"
> 
> it says:
> 
> `The Wikidata Query Service website automatically replaces [AUTO_LANGUAGE] with the language code of current user's interface. For example, if the user's UI is in French, the SPARQL's code bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" will be converted to bd:serviceParam wikibase:language "fr,en" before being sent to the query service.`
> 
> so it is basically happening in the UI. This means that we cannot implement it in the backend but we need a replacement in the front-end ....

In my specific application, I actually only need a single language output (such as Chinese). I'm using `AUTO_LANGUAGE` just because I want to find some simple examples to test if qEndpoint is working.  [This SPARQL tutorial](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial/) has lots of examples and they all use AUTO_LANGUAGE.

**Comment by sereyn** [comment]
> @sereyn would it be possible to grab some browser config and to do the replacement also in our front-end?

Yes, should I implement it?

**Comment by D063520** [comment]
@sereyn yes, not a priority, but should be a quick fix. I think you can read:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language

take the first part of the dash and replace AUTO_LANGUAGES
