### ISSUE TITLE
Wikidata HDT File Missing from univ-st-etienne Server

### ISSUE THREAD

**Issue by happen2me** [the-qa-company/qEndpoint#426]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [X] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the issue

When I run the wikidata version of the docker image, it fails to download the hdt files. It turns out that both the [truthy dump](https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt) and the [whole dump](https://qanswer-svc4.univ-st-etienne.fr/wikidata_all.hdt) are missing from https://qanswer-svc4.univ-st-etienne.fr.

I can not find the hdt file from anywhere else on the Internet, nor can I find the way to generate them from Wikidata's RDF dump. I'd really appreciate it if you could update the broken download link / infrastructure.

```
Downloading the HDT co-index wikidata_truthy into /app/qendpoint/hdt-store/index_dev.hdt.index.v1-1...
--2023-10-04 10:51:52--  https://qanswer-svc4.univ-st-etienne.fr/wikidata_truthy.hdt.index.v1-1
Resolving qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)... 161.3.151.12
Connecting to qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)|161.3.151.12|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-04 10:51:53 ERROR 404: Not Found.
```

### How to reproduce

Remove the local container and re-initialize it from docker hub.
```sh
docker rm qendpoint-wikidata
docker run -p 1234:1234 --name qendpoint-wikidata qacompany/qendpoint-wikidata
```

### Endpoint version

latest at the point of opening the issue

### Do I want to contribute to fix it?

Yes

**Comment by ate47** [comment]
Hello, it should be available, thank you for the notification.

**Comment by joelbarmettlerUZH** [comment]
@ate47 The qanswer-svc4.univ-st-etienne.fr again seems to return a 404 error, fyi

**Comment by joelbarmettlerUZH** [comment]
Is there an easy workaround? My current approach involves downloading the latest-truthy.nt.bz2 from wikidata, extracting it (results in a 992GB file) and then uploading it to /api/endpoint/load using curl, which takes forever. Is there a better way? Any hint is appreciated!

**Comment by ate47** [comment]
I don’t think you need to uncompress it. But you can also compress the HDT locally, upload it to your server and start the endpoint.

I am sorry, we reallocated the space storing the HDTs for an experiment.
