### ISSUE TITLE
Create the other indexes

### ISSUE THREAD

**Issue by ate47** [the-qa-company/qEndpoint#429]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [X] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the request

For now the FoQ index is giving access to pointers inside the SPO index to avoid having to take more space on the disk, I propose to create a SPO-like index for other the patterns (like OPS) so we don't rely on binary searches for the non-SPO patterns.

### Do I want to contribute to make it?

Yes

**Comment by D063520** [comment]
@ate47 great!!! Can you compress wikidata with the new indexes, so that we can try out some merge joins on top of it?
