### ISSUE TITLE
Allow to set the threashold in the query for maximum results retrieved from lucene

### ISSUE THREAD

**Issue by D063520** [the-qa-company/qEndpoint#485]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (qendpoint-backend)
- [X] Store (qendpoint-backend)
- [ ] Core (qendpoint-core)
- [ ] Frontend (qendpoint-frontend)
- [ ] Other

### Description of the request

When making a full-text query we limit the number of results retrieved from lucene. This  is set in the model-repo.ttl ,like

mdlc:luceneParam [
    mdlc:paramKey "maxDocuments" ;
    mdlc:paramValue "5000" ;
  ] ;

we would like to be able to overwrite this parameter at query time and not at setup time only.

### Do I want to contribute to make it?

No

### Something else?

https://github.com/ec-doris/kohesio-backend/issues/268

**Comment by ate47** [comment]
A threshold of what?

**Comment by D063520** [comment]
sorry, made the issue while beeing in a meeting so it was a bit rushed
