### ISSUE TITLE
Clarity in instructions: is pre-processing needed for Wikibase?

### ISSUE THREAD

**Issue by harej** [the-qa-company/qEndpoint#58]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-benchmark)
- [ ] Benchmark (hdt-qs-frontend)
- [ ] Other

### Description of the question

Typically, to ingest a Wikidata graph export into Blazegraph, you need to "munge" it using a script in order to transform the data into a more compact format. Is this needed when ingesting an NT into the HDT format?

**Comment by D063520** [comment]
Hi,

no this is not the case, you do not need any munge. We are twicking the load script though to arrive to ingest the whole wikidata dump.

What is exaclty your use case? If you need a SPARQL endpoint over Wikidata (only over the truthy statements) you can use this docker image:

https://hub.docker.com/r/qacompany/qendpoint-wikidata

which we published a week or so ago. Did you see it?

Salut
D063520
