### ISSUE TITLE
Load a custom application.properties file

### ISSUE THREAD

**Issue by harej** [the-qa-company/qEndpoint#60]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-benchmark)
- [ ] Benchmark (hdt-qs-frontend)
- [ ] Other

### Description of the question

I wrote a customized application.properties file that changes the port number and extends the timeout duration. When I run the JAR file I see it runs at the default port, suggesting to me the file isn't loading. I am not sure where to put the file to load it or what command line parameter to use.

**Comment by ate47** [comment]
To update the port and the timeouts, it was replaced with the repo model file, but the documentation isn't fixed yet.

By default this file is in `qendpoint/repo_model.ttl` and you can find the default version [here](https://github.com/the-qa-company/qEndpoint/blob/master/hdt-qs-backend/src/main/resources/repo_model.ttl) if you don't want to start the endpoint.

Simply uncomment these triples:

```turtle
# Describe the endpoint server port
mdlc:main mdlc:serverPort 1234 .

# Describe the maximum time for a non-update query (in seconds), 0 = infinity
mdlc:main mdlc:timeoutQuery 300 .

# Describe the maximum time for an update query (in seconds), 0 = infinity
mdlc:main mdlc:timeoutUpdate 300 .
```

**Comment by D063520** [comment]
I was also checking this out ... if we take the already compiled jar, is there a way to pass the configuration file when running java -jar qendpoint.jar?
