### ISSUE TITLE
wikidata docker image fails when internet connection lost

### ISSUE THREAD

**Issue by D063520** [the-qa-company/qEndpoint#68]
### Part of the endpoint? (leave empty if you don't know)

- [ ] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [x] Other

### Description of the issue

I closed my laptop while the container was running and I got:

/app/qendpoint/hdt-  50%[+++++++++>          ]  18.65G  5.60MB/s    in 2m 59s  

2022-07-21 15:56:24 (5.77 MB/s) - Connection closed at byte 20029579848. Retrying.

--2022-07-21 15:56:34--  (try:20)  https://qanswer-svc4.univ-st-etienne.fr/index_big.hdt.index.v1-1
Connecting to qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)|161.3.151.12|:443... failed: Connection refused.
Resolving qanswer-svc4.univ-st-etienne.fr (qanswer-svc4.univ-st-etienne.fr)... failed: Name or service not known.
wget: unable to resolve host address ‘qanswer-svc4.univ-st-etienne.fr’
/app/qendpoint/hdt-store/index_dev.hdt exists.

If I restart the container the enpoint is lunched, but the index is not ready ...

### Excepted behavior

the container should continue download the dump, maybe we can set a flag to indicate if the download was complete

**Comment by ate47** [comment]
I think downloading the HDT files into temp files before moving it to the store after the download will fix it

https://github.com/the-qa-company/qEndpoint/blob/master/scripts/loadData.sh

**Comment by D063520** [comment]
@DiaZork I think your fix does not work ... now there is a "-o" and a "-O" option ....

https://github.com/the-qa-company/qEndpoint/blob/master/scripts/loadData.sh
