### ISSUE TITLE
Wrong query result

### ISSUE THREAD

**Issue by D063520** [the-qa-company/qEndpoint#94]
### Part of the endpoint? (leave empty if you don't know)

- [X] Backend (hdt-qs-backend)
- [ ] Frontend (hdt-qs-frontend)
- [ ] Benchmark (hdt-qs-benchmark)
- [ ] Other

### Description of the issue

With the latest version of the endpoint when uploading:

[out.txt](https://github.com/the-qa-company/qEndpoint/files/9377187/out.txt)
(it's a nt file but github did not like it)

This query:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vrank:<http://purl.org/voc/vrank#> 
SELECT DISTINCT ?o (SAMPLE(?label) as ?l) (SAMPLE(?rank) as ?pageRank) {
  <http://qanswer.eu/node1> ?p ?o . ?o <http://purl.org/voc/vrank#pagerank> ?rank .  FILTER (?p != <http://purl.org/voc/vrank#pagerank>) OPTIONAL {?o <http://www.w3.org/2000/01/rdf-schema#label> ?label .  FILTER (lang(?label)="en" || lang(?label)="") } }GROUP BY ?o 
```

Is correct, but this is not:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vrank:<http://purl.org/voc/vrank#> 
SELECT DISTINCT ?o (SAMPLE(?label) as ?l) (SAMPLE(?rank) as ?pageRank) {
  <http://qanswer.eu/node1> ?p ?o . ?o <http://purl.org/voc/vrank#pagerank> ?rank .  FILTER (?p != <http://purl.org/voc/vrank#pagerank>) OPTIONAL {?o <http://www.w3.org/2000/01/rdf-schema#label> ?label .  FILTER (lang(?label)="en" || lang(?label)="") } }GROUP BY ?o ORDER BY DESC (?rank) LIMIT 5
```
5 results are expected but only one is returned.

### Endpoint version

1.5.3

### Do I want to contribute to fix it?

No

**Comment by ate47** [comment]
In the logs, I have:

```
org.eclipse.rdf4j.query.parser.sparql.ast.VisitorException: variable 'rank' in projection not present in GROUP BY.
```

I know RDF4J got some issues with the aggregation operations in 4.0.0, maybe we should try to update it to see if it fix the issue.

https://github.com/the-qa-company/qEndpoint/blob/db8cad5d9e1ee3305088829a2201c3462755bc97/hdt-qs-backend/pom.xml#L36

**Comment by D063520** [comment]
or downgrade, we can try ...

**Comment by D063520** [comment]
You solved it by upgrading?

**Comment by ate47** [comment]
Yes
